# LLP109: Digital Application Development 
# `Lecture 6- Python Practice (Numpy) Answer 2 (challenges)`


 ## Ch #1: 
 Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


In [50]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## Ch #2:
Create a 2D array subclass to create a symmetric matrix such that Z[i,j] == Z[j,i] 

Expected output: 
[[ 8  8  2  1  8]
 [ 8  0 13 12 13]
 [ 2 13  3 42  7]
 [ 1 12 42  8 11]
 [ 8 13  7 11  3]]

In [62]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  8  2  1  8]
 [ 8  0 13 12 13]
 [ 2 13  3 42  7]
 [ 1 12 42  8 11]
 [ 8 13  7 11  3]]


## Ch #3: 
10 fish occupy a 5x5x5 grid of water. Each fish decides to move to a new (i,j,k) location given by the matrix below. If multiple fish end up occupying the same cell, the biggest fish eats the smaller fish. Determine which fish will survive.

In [87]:
locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])
generator = np.random.default_rng(1010)
weights = generator.normal(2,size=10)
print(weights)

[0.30129983 2.53799701 1.77438601 0.90979106 2.55391264 0.49884555
 2.44545933 3.3448172  0.87635673 2.21216015]


In [88]:
sorted_fish = np.argsort(weights)[::-1]
uniques, first_idxs = np.unique(locs[sorted_fish], axis = 0, return_index = True)
survivors = sorted_fish[first_idxs]
print(survivors)

[7 1 9 3 6 4]
